variable_name_mapping = {
    # "STUDY"     : "study",
    # "WAVE"      : "wave", 
    # "RESPINT"   : "respondent_displayed_interest",
    "UNIQID"    : "respondent_id", 
    "CNTRY"     : "country_iso3166_num", 
    "CNTRY_AN"  : "country_iso3166_alpha2",
    "IVDATE"    : "interview_date", 
    "IVLENGTH"  : "interview_length", 
    "LNGE_ISO"  : "interview_language_iso639",
    "X001"      : "sex",
    "X002"      : "birthyear",
    "X003"      : "age",
    "G005"      : "citizenship",
    "G027A"     : "is_immigrant",
    # "X002_02A"  : "country_born_iso3166",
    # "V001"      : "father_is_immigrant",
    # "V002"      : "mother_is_immigrant",
    # "X007"      : "marital_status",
    # "X026_01"   : "lives_with_parents",
    # "X011"      : "amount_children",
    # "X013"      : "people_in_household",
    # "X025A_01"  : "education_level",
    # "X028"      : "employment_status",
    # "X052"      : "employment_institution_type",
    # "X047E_EVS5": "subjective_income_decile",
    # "A001"      : "family_importance",
    # "A002"      : "friends_importance",
    # "A003"      : "leisure_importance",
    # "A004"      : "politics_importance",
    # "A005"      : "work_importance",
    # "A006"      : "religion_importance",
    # "A008"      : "happiness_degree",
    # "A009"      : "subjective_health",
    # "A173"      : "perceived_freedom",
    # "A170"      : "life_satisfaction",
    # "A027"      : "child_manners_importance",
    # "A029"      : "child_independence_importance",
    # "A030"      : "child_hard_work_importance",
    # "A032"      : "child_responsibility_importance",
    # "A034"      : "child_imagination_importance",
    # "A035"      : "child_tolerant_importance",
    # "A038"      : "child_thrifty_importance",
    # "A039"      : "child_perseverance_importance",
    # "A040"      : "child_faith_importance",
    # "A041"      : "child_unselfish_importance",
    # "A042"      : "child_obedience_importance",
    # "A065"      : "member_regigious_org",
    # "A066"      : "member_cultural_org",
    # "A068"      : "member_political_party",
    # "A080_01"   : "member_charity_org",
    # "A080_02"   : "member_self_help_org",
    # "B008"      : "economic_vs_growth_environment",
    # "C001_01"   : "should_favour_men_if_job_scarcity",
    # "C002_01"   : "should_favour_nationals_if_job_scarcity",
    # "D081"      : "homosexual_couples_good_parents",
    # "D026_03"   : "having_children_duty_to_society",
    # "D026_05"   : "child_duty_care_for_ill_parent",
    # "C038"      : "unemployment_makes_lazy",
    # "C039"      : "work_should_be_top_priority",
    # "D054"      : "main_goal_making_parents_proud",
    # "D059"      : "men_better_polical_leaders",
    # "D078"      : "men_better_business_executives",
    # "E012"      : "willingness_fight_for_country",
    # "E023"      : "politics_interest",
    # "E035"      : "income_equality_view",
    # "E036"      : "private_ownership_view",
    # "E037"      : "government_responsibility_view",
    # "E039"      : "commercial_competition_view",
    # "E069_02"   : "armed_forces_confidence",
    # "E069_04"   : "media_confidence",
    # "E069_06"   : "police_confidence",
    # "E069_08"   : "civil_services_confidence",
    # "E069_11"   : "government_confidence",
    # "E069_13"   : "large_corporation_confidence",
    # "E069_14"   : "environmental_organizations_confidence",
    # "E069_17"   : "justice_system_confidence",
    # "E069_18"   : "european_union_confidence",
    # "E069_20"   : "united_nations_confidence",
    # "E111_01"   : "political_system_satisfaction",
    # "E235"      : "democracy_importance",
    # "E236"      : "country_feels_democratic",
    # "E264"      : "votes_in_elections",
    # "G006"      : "pride_in_nationality",
    # "F025"      : "religious_denomination",
    # "F034"      : "considers_oneself_religious",
    # "F050"      : "believe_in_god",
    # "F051"      : "believe_in_life_after_death",
    # "F054"      : "believe_in_heaven",
    # "F053"      : "believe_in_hell",
    # "F063"      : "god_personal_importance",
    # "F116"      : "tax_evasion_justifiable",
    # "F118"      : "homosexuality_justifiable",
    # "F119"      : "prostitution_justifiable",
    # "F120"      : "abortion_justifiable",
    # "F121"      : "divorce_justifiable",
    # "F122"      : "euthanasia_justifiable",
    # "F123"      : "suicide_justifiable",
    # "F132"      : "casual_sex_justifiable",
    # "F144_02"   : "death_penalty_justifiable",
    # "E290"      : "political_violence_justifiable",
    "A165"      : "most_people_trustworthy",
    # "D001_B"    : "trust_family",
    # "G007_33_B" : "trust_acquaintances",
    # "G007_34_B" : "trust_only_just_met",
    # "G007_35_B" : "trust_believers_of_other_religion",
    # "G007_36_B" : "trust_other_nationality",
    # "G052"      : "immigrants_impact",
    # "G063"      : "world_perceived_closeness",
    # "G257"      : "country_perceived_closeness",
    # "G255"      : "city_perceived_closeness",
}

variable_response_mapping = {
    "G005": { # Citizen of country
        0: False,
        1: True,
        2: False,
    },
    "G027A": { # Respondent immigrant / born in country
        1: "I am born in this country",
        2: "I am an immigrant to this country",
    },
    "X001": { # Sex
        1: "Male",
        2: "Female",
    },
    "X007": { # Marital status
        1: "Married",
        2: "Living together as married",
        3: "Divorced",
        4: "Separated",
        5: "Widowed",
        6: "Single/Never married",
    },
    "X026_01": { # Do you live with your parents?
        0: "No",
        1: "Yes",
    },
    "X011": { # How many children do you have?
        0: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: "6 or more",
    },
    "X013": { # Number of people in household
        0: 0,
        1: 1,
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: "6 or more",
    },
    "X025A_01": { # Highest educational level attained
        1: "No formal education",
        2: "Incomplete primary education",
        3: "Complete primary education",
        4: "Incomplete secondary education",
        5: "Complete secondary education",
        6: "Post-secondary education",
        7: "University degree",
    },
    "X028": { # Employment status Respondent
        1: "Full time (30h a week or more)",
        2: "Part time (less than 30 hours a week)",
        3: "Self-employed",
        4: "Retired/pensioned",
        5: "Housewife (not otherwise employed)",
        6: "Student",
        7: "Unemployed",
        8: "Other",
    },
    "X052": { # Institution of occupation
        1: "Public sector",
        2: "Private sector",
        3: "Self-employed",
        4: "Non-governmental organization (NGO)",
        5: "Other",
    },
    "X047E_EVS5": { # Scale of incomes (EVS5)
        1: "Lowest step",
        2: "Second step",
        3: "Third step",
        4: "Fourth step",
        5: "Fifth step",
        6: "Sixth step",
        7: "Seventh step",
        8: "Eighth step",
        9: "Ninth step",
        10: "Highest step",
    },
    "A001": { # Important in life: Family
        1: "Very important",
        2: "Rather important",
        3: "Not very important",
        4: "Not at all important",
    },
    "A002": { # Important in life: Friends
        1: "Very important",
        2: "Rather important",
        3: "Not very important",
        4: "Not at all important",
    },
    "A003": { # Important in life: Leisure time
        1: "Very important",
        2: "Rather important",
        3: "Not very important",
        4: "Not at all important",
    },
    "A004": { # Important in life: Politics
        1: "Very important",
        2: "Rather important",
        3: "Not very important",
        4: "Not at all important",
    },
    "A005": { # Important in life: Work
        1: "Very important",
        2: "Rather important",
        3: "Not very important",
        4: "Not at all important",
    },
    "A006": { # Important in life: Religion
        1: "Very important",
        2: "Rather important",
        3: "Not very important",
        4: "Not at all important"
    },
    "A008": { # Feeling of happiness
        1: "Very happy",
        2: "Rather happy",
        3: "Not very happy",
        4: "Not at all happy"
    },
    "A009": { # Subjective health
        1: "Very good",
        2: "Good",
        3: "Fair",
        4: "Poor",
        5: "Very poor",
    },
    "A173": { # Perceived freedom
        1: "None at all",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "A great deal",
    },
    "A170": { # Life satisfaction
        1: "Dissatisfied",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Satisfied",
    },
    "A027": { # Good manners important in children
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A029": { # Independence important in children
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A030": { # Work ethic important in children
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A032": { # Feeling responsibility important in children
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A034": { # Imagination important in children
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A035": { # Tolerance and respect for others important in children
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A038": { # Being thrifty important in children
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A039": { # Determination and perseverence important in children
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A040": { # Religious faith important in children
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A041": { # Unselfishness important in children
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A042": { # Obedience important in children
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A065": { # Member of religious organization
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A066": { # Member of cultural community
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A067": { # Member of labour union
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A068": { # Member of political party
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A071": { # Member of environmental organization
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A080_01": { # Member of humanitarian organization
        0: "Not mentioned",
        1: "Mentioned",
    },
    "A080_02": { # Member of self-help group
        0: "Not mentioned",
        1: "Mentioned",
    },
    "B008": { # Protect environment vs. economic growth
        "1": "Protecting environment",
        "2": "Economy growth and creating jobs",
        "3": "Other answer (if volunteered only)",
    },
    "C001_01": { # In case of job scarcity, men have more right to job than women
        1: "Strongly agree",
        2: "Agree",
        3: "Neither agree nor disagree",
        4: "Disagree",
        5: "Strongly disagree",
    },
    "C002_01": { # In case of job scarcity, nationals have more right to job than immigrants
        1: "Strongly agree",
        2: "Agree",
        3: "Neither agree nor disagree",
        4: "Disagree",
        5: "Strongly disagree",
    },
    "D081": { # Homosexuals are as good parents as other couples
        1: "Strongly agree",
        2: "Agree",
        3: "Neither agree nor disagree",
        4: "Disagree",
        5: "Strongly disagree",
    },
    "D026_03": { # Having children is duty towards society
        1: "Strongly agree",
        2: "Agree",
        3: "Neither agree nor disagree",
        4: "Disagree",
        5: "Strongly disagree",
    },
    "D026_05": { # Is duty of child to care for ill parent
        1: "Strongly agree",
        2: "Agree",
        3: "Neither agree nor disagree",
        4: "Disagree",
        5: "Strongly disagree",
    },
    "C038": { # Being unemployed makes one lazy
        1: "Strongly agree",
        2: "Agree",
        3: "Neither agree nor disagree",
        4: "Disagree",
        5: "Strongly disagree",
    },
    "C039": { # Homosexuals are as good parents as other couples
        1: "Strongly agree",
        2: "Agree",
        3: "Neither agree nor disagree",
        4: "Disagree",
        5: "Strongly disagree",
    },
    "D054": { # Making parents proud has been one of main goals
        1: "Strongly agree",
        2: "Agree",
        3: "Disagree",
        4: "Strongly disagree",
    },
    "D059": { # Men make better political leaders than women
        1: "Strongly agree",
        2: "Agree",
        3: "Disagree",
        4: "Strongly disagree",
    },
    "D078": { # Men make better business executives than women
        1: "Strongly agree",
        2: "Agree",
        3: "Disagree",
        4: "Strongly disagree",
    },
    "E012": { # Willing to fight for country
        0: "No",
        1: "Yes",
    },
    "E023": { # Interest in politics
        1: "Very interested",
        2: "Somewhat interested",
        3: "Not very interested",
        4: "Not at all interested",
    },
    "E035": { # View on income equality 
        1: "Incomes should be made more equal",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "We need larger income differences as incentives",
    },
    "E036": { # View on private ownership
        1: "Private ownership of businesses should be increased",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Private ownership of businesses should be decreased",
    },
    "E037": { # View on government responsibility
        1: "People should take more responsibility",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "The government should take more responsibility",
    },
    "E039": { # View on market competition
        1: "Competition is good",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Competition is harmful",
    },
    "E069_02": { # Confidence in armed forces
        1: "A great deal",
        2: "Quite a lot",
        3: "Not very much",
        4: "None at all",
    },
    "E069_04": { # Confidence in the media
        1: "A great deal",
        2: "Quite a lot",
        3: "Not very much",
        4: "None at all",
    },
    "E069_06": { # Confidence in the police
        1: "A great deal",
        2: "Quite a lot",
        3: "Not very much",
        4: "None at all",
    },
    "E069_08": { # Confidence in civil services
        1: "A great deal",
        2: "Quite a lot",
        3: "Not very much",
        4: "None at all",
    },
    "E069_11": { # Confidence in government
        1: "A great deal",
        2: "Quite a lot",
        3: "Not very much",
        4: "None at all",
    },
    "E069_13": { # Confidence in large corporations
        1: "A great deal",
        2: "Quite a lot",
        3: "Not very much",
        4: "None at all",
    },
    "E069_14": { # Confidence in environmental protection organizations
        1: "A great deal",
        2: "Quite a lot",
        3: "Not very much",
        4: "None at all",
    },
    "E069_17": { # Confidence in justice system
        1: "A great deal",
        2: "Quite a lot",
        3: "Not very much",
        4: "None at all",
    },
    "E069_18": { # Confidence in the European Union
        1: "A great deal",
        2: "Quite a lot",
        3: "Not very much",
        4: "None at all",
    },
    "E069_20": { # Confidence in the United Nations
        1: "A great deal",
        2: "Quite a lot",
        3: "Not very much",
        4: "None at all",
    },
    "E111_01": { # Satisfaction with political system
        1: "Not satisfied at all",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Completely satisfied",
    },
    "E235": { # Importance of democracy
        1: "Not at all important",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Absolutely important",
    },
    "E236": { # Home country feels like it's being democratically run
        1: "Not at all democratic",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Completely democratic",
    },
    "E264": { # Does vote in national elections
        1: "Always",
        2: "Usually",
        3: "Never",
        4: "Not allowed to vote",
    },
    "F025": { # Religious denomination
        0: "None (do not belong to any religious denomination)",
        1: "Roman Catholic",
        2: "Protestant",
        3: "Orthodox",
        4: "Jew",
        5: "Muslim",
        6: "Hindu",
        7: "Buddhist",
        8: "Other Christian (Evangelical, Pentecostal, Free Church etc.)",
        9: "Other",
    },
    "F034": { # Consider oneself religious
        1: "A religious person",
        2: "Not a religious person",
        3: "A convinced atheist",
    },
    "F050": { # Believe in god
        0: "No",
        1: "Yes",
    },
    "F051": { # Believe in life after death
        0: "No",
        1: "Yes",
    },
    "F053": { # Believe in hell
        0: "No",
        1: "Yes",
    },
    "F054": { # Believe in heaven
        0: "No",
        1: "Yes",
    },
    "F063": { # How important god is in one's life
        1: "Not at all important",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Very important",
    },
    "F116": { # Justifiability of tax evasion
        1: "Never justifiable",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Always justifiable",
    },
    "F118": { # Justifiability of homosexuality
        1: "Never justifiable",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Always justifiable",
    },
    "F119": { # Justifiability of prostitution
        1: "Never justifiable",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Always justifiable",
    },
    "F120": { # Justifiability of abortion
        1: "Never justifiable",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Always justifiable",
    },
    "F121": { # Justifiability of divorce
        1: "Never justifiable",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Always justifiable",
    },
    "F122": { # Justifiability of euthanasia
        1: "Never justifiable",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Always justifiable",
    },
    "F123": { # Justifiability of suicide
        1: "Never justifiable",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Always justifiable",
    },
    "F132": { # Justifiability of casual_sex
        1: "Never justifiable",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Always justifiable",
    },
    "F144_02": { # Justifiability of death_penalty
        1: "Never justifiable",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Always justifiable",
    },
    "E290": { # Justifiability of political violence
        1: "Never justifiable",
        2: 2,
        3: 3,
        4: 4,
        5: 5,
        6: 6,
        7: 7,
        8: 8,
        9: 9,
        10: "Always justifiable",
    },
    "A165": { # Most people can be trusted
        1: "Most people can be trusted",
        2: "Can't be too careful",
    },
    "D001_B": { # Trust in family
        1: "Trust completely",
        2: "Trust somewhat",
        3: "Do not trust very much",
        4: "Do not trust at all",
    },
    "G006": { # Pride in nationality
        1: "Very proud",
        2: "Quite proud",
        3: "Not very proud",
        4: "Not at all proud"
    },
    "G007_33_B": { # Trust in family
        1: "Trust completely",
        2: "Trust somewhat",
        3: "Do not trust very much",
        4: "Do not trust at all",
    },
    "G007_34_B": { # Trust in people you meet for the first time
        1: "Trust completely",
        2: "Trust somewhat",
        3: "Do not trust very much",
        4: "Do not trust at all",
    },
    "G007_35_B": { # Trust in people of other religion
        1: "Trust completely",
        2: "Trust somewhat",
        3: "Do not trust very much",
        4: "Do not trust at all",
    },
    "G007_36_B": { # Trust in people of other nationality
        1: "Trust completely",
        2: "Trust somewhat",
        3: "Do not trust very much",
        4: "Do not trust at all",
    },
    "G052": { # Impact of immigrants on own country
        1: "Very bad",
        2: "Quite bad",
        3: "Neither good nor bad",
        4: "Quite good",
        5: "Very good"
    },
    "G063": { # Perceived closeness to the world
        1: "Very close",
        2: "Close",
        3: "Not very close",
        4: "Not close at all"
    },
    "G257": { # Perceived closeness to own country
        1: "Very close",
        2: "Close",
        3: "Not very close",
        4: "Not close at all"
    },
    "G255": { # Perceived closeness to own city
        1: "Very close",
        2: "Close",
        3: "Not very close",
        4: "Not close at all"
    },
}

for mapping in variable_response_mapping:
    variable_response_mapping[mapping].update({
        -5: "Missing: Other",
        -4: "Not asked in survey",
        -3: "Not applicable",
        -2: "No answer",
        -1: "Don't know",
    })
